name: Image Sync Action
description: Sync images from source registry to target registry.
branding:
  icon: refresh-cw
  color: blue
inputs:
  target-registry-url:
    description: "URL of the target image registry"
    required: true
    default: "registry.cn-hangzhou.aliyuncs.com"
  target-registry-namespace:
    description: "Namespace of the target image registry"
    required: true
    default: "code-crafters-lab"
  docker-username:
    description: "Username for docker registry authentication"
    required: true
  docker-password:
    description: "Password for docker registry authentication"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target-registry-url }}
    - ${{ inputs.target-registry-namespace }}
    - ${{ inputs.docker-username }}
    - ${{ inputs.docker-password }}