name: Build Image Toolkit for Multiple Systems
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ windows, linux, darwin ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-24.04
    env:
      GOPATH: ${{ github.workspace }}
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build binary for ${{ matrix.os }}-${{ matrix.arch }}${{ env.GOEXE }}
        run: |
          go build -o image-toolkit-${{ matrix.os }}-${{ matrix.arch }}${{ env.GOEXE }} main.go
          ls -lh image-toolkit-${{ matrix.os }}-${{ matrix.arch }}*
          echo "Build completed for ${{ matrix.os }}-${{ matrix.arch }}${{ env.GOEXE }}"

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-toolkit-${{ matrix.os }}-${{ matrix.arch }}${{ env.GOEXE }}
          path: ${{ github.workspace }}/image-toolkit-${{ matrix.os }}-${{ matrix.arch }}${{ env.GOEXE }}
