name: Build Image Toolkit for Multiple Systems
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        goos: [ windows,linux, darwin ]
        goarch: [ amd64, arm64 ]
        go-version: [ 1.22 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary for ${{ matrix.os }}
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            GOOS=windows GOARCH=amd64 go build -o myapp.exe
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            GOOS=darwin GOARCH=amd64 go build -o myapp
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            GOOS=linux GOARCH=amd64 go build -o myapp
          fi
        env:
          GOPATH: ${{ github.workspace }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.os }}
          path: |
            myapp*